"""Article embeddings: one dense vector per article, one interface per dataset.

How the vectors are obtained differs — MIND has none and they are generated by
a notebook on a hosted GPU, EB-NeRD ships precomputed multilingual BERT — but
that difference lives in the registry's EmbeddingSpec. Everything below reads
the spec and never the dataset name.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path

import numpy as np
import pandas as pd

from pipeline.datasets import DatasetConfig, EmbeddingSpec

# float32 normalisation lands a few ulps off exactly 1.0; anything further out
# than this is a real deviation rather than rounding.
UNIT_TOLERANCE = 1e-5


# The two ways a dataset comes by its vectors, as named in the registry.
GENERATE, PROVIDED = "generate", "provided"

# The article-id-to-row index, saved beside the vectors. The notebook emits
# one of these for MIND and the stage writes one for either dataset.
ID_INDEX = "article_id_index.parquet"

# The aligned, unit-length matrix the stage writes for ticket 8 to load. Named
# apart from the registry's `artifact` so saving it can never overwrite the
# downloaded source it was built from.
VECTORS = "vectors.npy"
# What produced a cached corpus matrix. Beside it rather than in its name, so
# a stale cache is *replaced* rather than accumulating one directory per model.
SOURCE = "source.json"

# What this stage derives lives in a subdirectory of the dataset's artifacts,
# as ticket 6's index does. The downloaded source stays at the root, so saving
# an id index in corpus order can never land on the notebook-ordered one it
# was built from -- which would pair every MIND vector with another article on
# the next forced run, and score plausibly while being entirely wrong.
EMBED_DIR = "embed"

# The notebook that produces the generated artifact, named in the error a user
# hits when it has not been run yet.
NOTEBOOK = "notebooks/generate_mind_embeddings.ipynb"


class EmbeddingError(RuntimeError):
    """The embedding artifact does not hold what the pipeline requires of it."""


def output_dir(config: DatasetConfig) -> Path:
    """Where this stage's own files go, apart from any downloaded source."""
    return config.artifacts_dir / EMBED_DIR


def document_text(articles: pd.DataFrame) -> pd.Series:
    """The text an article is encoded from: its title, then its abstract.

    Not `lexical_text`, which preprocess stripped of stopwords and case for
    BM25's benefit -- a sentence transformer is trained on running prose and
    reads the stripped form as a worse sentence. This is the one definition of
    what the vectors mean; the generation notebook imports it rather than
    reproducing it, because a notebook that drifts from this line would encode
    something the pipeline does not think it holds.
    """
    title = articles["title"].fillna("").str.strip()
    abstract = articles["abstract"].fillna("").str.strip()
    # 3,415 of MIND's 65,238 articles have no abstract. Joining unconditionally
    # would leave them with a trailing separator, and trimming that back off
    # would take the full stop off a title that ends in an abbreviation too.
    return title.where(abstract == "", title + ". " + abstract)


def cls_pool(hidden: "torch.Tensor", attention_mask: "torch.Tensor") -> "torch.Tensor":
    """The first token's vector, which is what BERT's [CLS] position holds.

    `bge-*-v1.5` is trained to put the sentence representation here, and mean
    pooling it instead returns a perfectly well-formed vector that is not the
    model's. The mask is unused -- position 0 is never padding -- and taken
    only so the two poolers are interchangeable by name.
    """
    del attention_mask
    return hidden[:, 0]


def mean_pool(hidden: "torch.Tensor", attention_mask: "torch.Tensor") -> "torch.Tensor":
    """Average a sequence's token vectors, counting only the real tokens.

    Padding is what makes this more than a mean: a batch is padded to its
    longest text, and averaging over the padding too would shrink every short
    document's vector toward zero by a factor that depends on what happened to
    be batched alongside it -- so the same article would embed differently on
    a different batch boundary.
    """
    mask = attention_mask.unsqueeze(-1).to(hidden.dtype)
    return (hidden * mask).sum(1) / mask.sum(1).clamp(min=1e-9)


# Words as word2vec sees them: it is case-sensitive and has vectors for
# stopwords, so `preprocess.cleaner` is the wrong tokeniser here -- it lowers
# case and strips exactly the words the model has entries for. Apostrophes stay
# inside a token because GoogleNews holds "don't" and not "don" plus "t".
WORD = re.compile(r"[A-Za-z][A-Za-z'-]*")


def encode_word2vec(texts: list[str], model_dir: Path, dim: int) -> np.ndarray:
    """Document vectors as the mean of their words' pre-trained vectors.

    The floor the assignment asks for, and on EB-NeRD the *winner*: its shipped
    word2vec artifact at 300 dimensions beat three transformers at 768. Which
    is why this is here as a real comparison rather than a formality.

    A word the model does not know contributes nothing rather than a zero
    vector -- the same argument `build_user_vectors` makes about clicks the
    catalogue has no row for. A document with no known word at all comes back
    as a zero row, which `normalise` leaves at zero and the retriever reads as
    a user it knows nothing about.

    Case is tried before lowercase, because GoogleNews distinguishes them and
    "Apple" is not "apple" in it.
    """
    from gensim.models import KeyedVectors

    vectors = KeyedVectors.load(str(model_dir), mmap="r")
    matrix = np.zeros((len(texts), dim), dtype="float32")
    for row, text in enumerate(texts):
        found = [
            vectors[word] if word in vectors else vectors[word.lower()]
            for word in WORD.findall(text)
            if word in vectors or word.lower() in vectors
        ]
        if found:
            matrix[row] = np.mean(found, axis=0)
    return matrix


POOLERS = {"mean": mean_pool, "cls": cls_pool}


def encode(texts: list[str], config: DatasetConfig, device: str = "cpu",
           batch_size: int = 256, spec: EmbeddingSpec | None = None) -> np.ndarray:
    """Encode documents into unit-length vectors, for a dataset that generates.

    This is the whole of what the `sentence-transformers` wrapper does for a
    checkpoint of this shape -- tokenise, run the encoder, pool, L2 normalise --
    run against `transformers` directly. Verified equal to that wrapper's output
    on 256 real MIND articles to 9.3e-08, which is float32 rounding. Doing it
    means the notebook that runs on a hosted GPU installs nothing: Colab already
    ships torch and transformers, and pip re-pinning numpy underneath a live
    kernel is what broke that notebook twice.

    Two things vary by checkpoint and neither errors when it is wrong, which is
    why both are registry fields read here rather than constants: the **pooling**
    (`bge-*` reads CLS where the sentence-transformers models read the mean) and
    the **prefix** (e5 requires one on every input). Get either wrong and the
    vectors are well-formed, unit length, and not the model's -- the experiment
    then reports a good encoder as a bad one.

    `spec` overrides the registry's active entry, which is how phase 7 encodes
    the variants: the same path, one model at a time, with no stage branching on
    which checkpoint it holds.

    Imported lazily, like the gdown fetch below, because the pipeline itself
    rarely encodes -- a dataset that generates its vectors downloads them, and
    only the notebook and the encode job take this path.
    """
    import torch
    from tqdm import tqdm
    from transformers import AutoModel, AutoTokenizer

    spec = spec or config.embeddings
    if spec.pooling not in POOLERS:
        raise EmbeddingError(
            f"unknown pooling {spec.pooling!r}, expected one of "
            f"{', '.join(POOLERS)}"
        )
    pool = POOLERS[spec.pooling]

    tokenizer = AutoTokenizer.from_pretrained(spec.model)
    model = AutoModel.from_pretrained(spec.model).to(device).eval()

    # Prefixed before truncation, so a long article loses its tail rather than
    # its instruction -- the other order would drop the prefix from exactly the
    # documents that fill the window.
    if spec.prefix:
        texts = [spec.prefix + text for text in texts]

    rows = []
    with torch.no_grad():
        for start in tqdm(range(0, len(texts), batch_size), unit="batch"):
            batch = tokenizer(
                texts[start : start + batch_size],
                padding=True,
                truncation=True,
                max_length=spec.max_tokens,
                return_tensors="pt",
            ).to(device)
            pooled = pool(
                model(**batch).last_hidden_state, batch["attention_mask"]
            )
            rows.append(torch.nn.functional.normalize(pooled, p=2, dim=1).cpu())

    return torch.cat(rows).numpy().astype("float32")


def align(
    source_ids: np.ndarray,
    source_vectors: np.ndarray,
    corpus_ids: pd.Series,
    dim: int,
) -> tuple[np.ndarray, int]:
    """Reorder the source vectors onto the corpus, one row per article.

    The corpus decides which rows exist and in what order; the artifact is
    only asked what it holds for each. Vectors for articles outside the corpus
    are dropped, and an article the artifact has no vector for keeps its row
    as zeros rather than vanishing — a missing row would put the corpus and
    the matrix permanently out of step, and a zero vector scores zero against
    everything, so it is never retrieved on evidence it does not have.
    """
    row_of = {article_id: row for row, article_id in enumerate(source_ids)}
    matrix = np.zeros((len(corpus_ids), dim), dtype="float32")

    missing = 0
    for row, article_id in enumerate(corpus_ids):
        source_row = row_of.get(article_id)
        if source_row is None:
            missing += 1
            continue
        matrix[row] = source_vectors[source_row]

    return matrix, missing


def stale_rows(config: DatasetConfig, articles: pd.DataFrame) -> np.ndarray:
    """Corpus rows whose text is not the text their artifact vector came from.

    `align` pairs the artifact to a corpus by `article_id`, which is only a
    valid key while an id means the same article on both sides. Across MIND
    releases it does not: of the 60,609 ids MINDsmall and MINDlarge_test share,
    **60,608 are different articles**, so aligning by id alone gave the
    submission a catalogue half of which held some unrelated article's vector.
    An id is a per-release local name in MIND and a stable one in EB-NeRD, and
    nothing about either says which it is.

    So the id is checked against the thing that actually has to be true for a
    vector to be reusable -- that it was built from this text. Where the two
    disagree the row is dropped rather than trusted, and `for_corpus` encodes
    it again if the dataset can. A zero row is never retrieved; a confidently
    wrong one is, which is the failure this exists against.

    Compared against the feature store's catalogue, because that is what the
    artifact was encoded from -- `encode_variants.texts_for` reads exactly this
    file, through this same `document_text`. An id the feature store does not
    hold has nothing to contradict it and is left alone: either the artifact
    has no row for it either, or the artifact ships with the release and covers
    articles the feature store never saw, which is EB-NeRD's case.
    """
    catalogue = config.feature_store_dir / "articles.parquet"
    if not catalogue.exists():
        # Nothing to check against. The artifact is generated *from* this file,
        # so in practice it is here whenever there is an artifact to reuse.
        return np.zeros(len(articles), dtype=bool)

    known = pd.read_parquet(catalogue, columns=["article_id", "title", "abstract"])
    was = dict(zip(known["article_id"].astype("string"), document_text(known)))
    return np.array(
        [
            was.get(article_id, text) != text
            for article_id, text in zip(
                articles["article_id"].astype("string"), document_text(articles)
            )
        ],
        dtype=bool,
    )


def normalise(matrix: np.ndarray) -> np.ndarray:
    """Scale every row to unit length, so an inner product is a cosine.

    Rows that are already zero — the articles align found no vector for —
    stay zero rather than becoming NaN. Dividing them through would spread
    NaN across every score the index ever computes, whereas a zero row simply
    never wins a comparison.
    """
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return np.divide(matrix, norms, out=np.zeros_like(matrix), where=norms > 0)


# Rows sampled when measuring geometry. The statistic is a mean over pairs, so
# it costs the square of this; 3,000 rows is 9M pairs, which is milliseconds,
# and the sample error at that size is far below the difference the statistic
# exists to show (0.06 against 0.95).
ANISOTROPY_SAMPLE = 3_000
ANISOTROPY_SEED = 0


def anisotropy(matrix: np.ndarray, sample: int = ANISOTROPY_SAMPLE) -> float:
    """Mean cosine between two different rows drawn from this matrix.

    Near 0 means the vectors point in all directions and a cosine between two
    of them is informative. Near 1 means they occupy a narrow cone, every pair
    looks alike whatever the articles say, and the real signal is a rounding
    error riding on a large constant -- which is what EB-NeRD's shipped mBERT
    vectors do, and why its semantic retriever ranks at chance.

    The diagonal is excluded: a row's cosine with itself is 1 by construction
    and counting it would report a floor of 1/n rather than anything about the
    cloud. Zero rows -- articles `align` found no vector for -- are dropped
    too, since they are an absence rather than a direction.

    Sampled on a large corpus, and seeded, because a figure printed in a build
    log that moved between runs would read as the vectors having changed.
    """
    rows = matrix[np.linalg.norm(matrix, axis=1) > 0]
    if len(rows) < 2:
        return 0.0
    if len(rows) > sample:
        rng = np.random.default_rng(ANISOTROPY_SEED)
        rows = rows[rng.choice(len(rows), sample, replace=False)]

    unit = normalise(rows.astype("float32"))
    similarity = unit @ unit.T
    off_diagonal = ~np.eye(len(unit), dtype=bool)
    return float(similarity[off_diagonal].mean())


# Post-processing methods. `abtt` takes a component count after a colon.
POSTPROCESS = ("none", "centre", "abtt", "whiten")

# Rows the whitening and component estimates are fitted on. The statistics are
# a property of the corpus, so they are fitted over the corpus -- but a corpus
# of 125,541 vectors does not need all of them to estimate a mean and a handful
# of principal directions.
FIT_SAMPLE = 20_000


def _fit_rows(matrix: np.ndarray) -> np.ndarray:
    """The non-zero rows the statistics are estimated from, sampled and seeded.

    Zero rows are excluded: they are articles the artifact had no vector for,
    and averaging an absence into the mean would drag the correction toward a
    direction no article actually points in.
    """
    rows = matrix[np.linalg.norm(matrix, axis=1) > 0]
    if len(rows) > FIT_SAMPLE:
        rng = np.random.default_rng(ANISOTROPY_SEED)
        rows = rows[rng.choice(len(rows), FIT_SAMPLE, replace=False)]
    return rows.astype("float32")


def postprocess(matrix: np.ndarray, method: str) -> np.ndarray:
    """Correct the geometry of an embedding matrix, then rescale to unit length.

    Raw transformer output occupies a narrow cone rather than a ball: every
    pair of vectors has a high cosine whatever the two articles say, so the
    signal a retriever needs rides as a small residual on a large shared
    offset. These are the standard training-free corrections for that.

        none     leave the vectors as they arrived
        centre   subtract the corpus mean, which removes the shared offset
        abtt:n   all-but-the-top: the mean, then the n leading principal
                 directions. mBERT's anisotropy is distributed rather than
                 concentrated in a few outlier dimensions, so clipping
                 dimensions does not work and n is a real choice
        whiten   decorrelate the covariance, which is the strongest of the
                 four and the one that also equalises the variances

    Whatever is chosen, an article that had no vector keeps its zero row: a
    zero row never wins a comparison, whereas a centred one would point away
    from everything, which is a confident claim about an article nothing is
    known about.
    """
    name, _, argument = method.partition(":")
    if name not in POSTPROCESS:
        raise EmbeddingError(
            f"unknown embedding post-processing {method!r}; use one of: "
            f"{', '.join(POSTPROCESS)} (abtt takes a component count, e.g. "
            f"abtt:3)"
        )
    if name == "none":
        return matrix

    present = np.linalg.norm(matrix, axis=1) > 0
    fitted = _fit_rows(matrix)
    if len(fitted) < 2:
        return matrix

    centred = matrix.astype("float32") - fitted.mean(axis=0)

    if name == "abtt":
        components = int(argument) if argument else 1
        # Removing as many directions as the sample has leaves nothing behind:
        # every row becomes zero, which passes the unit-norm check (it skips
        # zero rows) and produces a retriever that silently scores everything
        # the same. Real corpora are far above this, but a toy one is not.
        components = min(components, len(fitted) - 1, matrix.shape[1] - 1)
        if components < 1:
            return matrix
        # Estimated on the centred sample, so they are directions of variation
        # rather than of the offset that has already been removed.
        _, _, directions = np.linalg.svd(
            fitted - fitted.mean(axis=0), full_matrices=False
        )
        top = directions[:components]
        centred = centred - (centred @ top.T) @ top
    elif name == "whiten":
        sample = fitted - fitted.mean(axis=0)
        covariance = np.cov(sample, rowvar=False)
        values, vectors = np.linalg.eigh(covariance)
        # Guard the small eigenvalues: dividing by one near zero amplifies a
        # direction that is noise, which un-corrects what this is here to fix.
        scale = 1.0 / np.sqrt(np.maximum(values, 1e-8))
        centred = centred @ (vectors * scale) @ vectors.T

    corrected = normalise(centred.astype("float32"))
    corrected[~present] = 0.0
    return corrected


def check_unit_norm(matrix: np.ndarray, config: DatasetConfig) -> None:
    """Every non-zero row must have length one, whoever produced it.

    For EB-NeRD this confirms our own normalisation; for MIND it confirms the
    notebook's `normalize_embeddings=True` actually took effect in the
    artifact that got uploaded, which is otherwise only knowable by reading a
    notebook that ran on someone else's machine.
    """
    norms = np.linalg.norm(matrix, axis=1)
    off = np.abs(norms - 1.0) > UNIT_TOLERANCE
    # A zero row is align reporting a missing vector, not a scaling failure.
    off &= norms > 0

    if off.any():
        worst = norms[off]
        raise EmbeddingError(
            f"{config.name}: {off.sum():,} of {len(norms):,} embedding rows "
            f"are not unit length (norms {worst.min():.4g} to {worst.max():.4g}); "
            f"an inner product over these is not a cosine similarity"
        )


def read_source(config: DatasetConfig) -> tuple[np.ndarray, np.ndarray]:
    """The dataset's vectors as (article ids, matrix), straight from its source.

    Neither the order nor the membership is the corpus's — EB-NeRD's artifact
    covers the whole release, not just the small distribution — so what comes
    back here is only ever handed to `align`.
    """
    spec = config.embeddings
    if spec.kind == PROVIDED:
        frame = pd.read_parquet(config.raw_dir / spec.artifact)
        # The artifact carries the ids and exactly one vector column, named
        # after the model that produced it. Naming that column in the registry
        # too would be a second thing to keep in step with the file.
        columns = [name for name in frame.columns if name != "article_id"]
        if len(columns) != 1:
            raise EmbeddingError(
                f"{config.name}: expected one vector column beside article_id "
                f"in {spec.artifact}, found {columns}"
            )
        vectors = np.stack(
            [np.asarray(row, dtype="float32") for row in frame[columns[0]]]
        )
    else:
        vectors = np.load(config.artifacts_dir / spec.artifact).astype("float32")
        frame = pd.read_parquet(config.artifacts_dir / ID_INDEX)

    # The corpus keys articles by string; EB-NeRD's artifact keys them by
    # int32. Unconverted, align would match nothing and hand back a matrix of
    # zeros that every later stage would read as a very poor retriever.
    return frame["article_id"].astype("string").to_numpy(dtype=object), vectors


@dataclass(frozen=True)
class Embeddings:
    """One dataset's article vectors, and what turns an id into a row.

    Row i belongs to article_ids[i], and article_ids is the article catalogue
    in catalogue order — so a row number and a catalogue position are the same
    thing, whichever way the dataset came by its vectors.
    """

    vectors: np.ndarray
    article_ids: np.ndarray

    @cached_property
    def index(self) -> dict[str, int]:
        """article id -> row. Built once; ticket 8 does a lookup per click."""
        return {article_id: row for row, article_id in enumerate(self.article_ids)}

    def save(self, directory: Path) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        np.save(directory / VECTORS, self.vectors)
        pd.DataFrame({"article_id": pd.Series(self.article_ids, dtype="string")}
                     ).to_parquet(directory / ID_INDEX, index=False)


def build(articles: pd.DataFrame, config: DatasetConfig) -> tuple[Embeddings, dict]:
    """The dataset's vectors, aligned to its catalogue and unit length.

    Whether the scaling happens here or happened upstream is a registry
    decision; that it holds afterwards is checked either way, because ticket
    8 calls the inner product of these a cosine similarity.
    """
    spec = config.embeddings
    source_ids, source_vectors = read_source(config)

    width = source_vectors.shape[1]
    if width != spec.dim:
        raise EmbeddingError(
            f"{config.name}: {spec.artifact} holds {width}-dimensional "
            f"vectors, but the registry declares {spec.dim}"
        )

    corpus_ids = articles["article_id"]
    matrix, missing = align(source_ids, source_vectors, corpus_ids, spec.dim)
    if spec.normalise:
        matrix = normalise(matrix)

    # Measured before the correction as well as after, so the build log says
    # what the source vectors were like and not only what they became.
    before = anisotropy(matrix)
    matrix = postprocess(matrix, spec.postprocess)
    check_unit_norm(matrix, config)

    embeddings = Embeddings(
        vectors=matrix, article_ids=corpus_ids.to_numpy(dtype=object)
    )
    report = {
        "articles": len(corpus_ids),
        "dim": matrix.shape[1],
        "missing": missing,
        "postprocess": spec.postprocess,
        "anisotropy_before": before,
        "anisotropy_after": anisotropy(matrix),
    }
    return embeddings, report


def ensure_artifact(config: DatasetConfig) -> None:
    """Put the generated artifact on disk if it is not already there.

    A dataset whose vectors ship with it has nothing to fetch. For one that
    generates them, the artifact is a build output rather than source, so it
    is downloaded on demand instead of being committed — and once it is here
    it is used as it stands, with no network call to confirm it.
    """
    spec = config.embeddings
    if spec.kind != GENERATE:
        return

    vectors = config.artifacts_dir / spec.artifact
    index = config.artifacts_dir / ID_INDEX
    if vectors.exists() and index.exists():
        return

    if spec.gdrive_file_id is None:
        raise EmbeddingError(
            f"{config.name}: no embeddings on disk and no artifact to fetch.\n"
            f"  {config.name} ships no vectors, so they are generated once on a "
            f"GPU rather than rebuilt on every machine. Produce "
            f"{spec.artifact} with:\n"
            f"    sbatch ada/encode.sbatch --variant '{spec.name}'\n"
            f"  or, off the cluster:\n"
            f"    python -m pipeline.encode_variants --dataset {config.name} "
            f"--variant '{spec.name}' --device cuda\n"
            f"  Either writes it beside {ID_INDEX}, which fixes the row order.\n"
            f"  To fetch a pre-built one instead, put its Drive folder id in "
            f"gdrive_file_id on {config.name}'s EmbeddingSpec in "
            f"pipeline/datasets.py -- {NOTEBOOK} is the older route and "
            f"produces the all-MiniLM-L6-v2 artifact, not this one.\n"
            f"  then re-run this stage."
        )

    # Imported here because it is only ever needed on the one path that
    # downloads, and only until the artifact is cached locally.
    import gdown

    config.artifacts_dir.mkdir(parents=True, exist_ok=True)
    gdown.download_folder(
        id=spec.gdrive_file_id, output=str(config.artifacts_dir), quiet=False
    )

    absent = [path.name for path in (vectors, index) if not path.exists()]
    if absent:
        raise EmbeddingError(
            f"{config.name}: the download from Drive folder "
            f"{spec.gdrive_file_id} left no {', '.join(absent)} in "
            f"{config.artifacts_dir}"
        )


def encoding_device() -> str:
    """`cuda` where the machine has one, `cpu` otherwise.

    The submission path encodes whatever the stored artifact does not cover --
    60,352 of MINDlarge_test's 120,961 articles -- and did it on the CPU even
    when a GPU was attached, because the device defaulted and nothing passed
    one. Measured on Ada: 14 texts/s that way against 140 on a GTX 1080 Ti, so
    a 72-minute step where seven would do.

    torch is imported here rather than at module scope for the same reason
    `encode` does it: the pipeline mostly loads cached vectors and never needs
    torch at all.
    """
    try:
        import torch
    except ImportError:
        return "cpu"
    return "cuda" if torch.cuda.is_available() else "cpu"


def for_corpus(
    articles: pd.DataFrame, config: DatasetConfig, directory: Path
) -> tuple[Embeddings, dict[str, int]]:
    """Vectors for a corpus the stored artifact need not cover, cached here.

    `build` aligns the artifact onto whatever corpus it is given and leaves a
    zero row wherever it holds nothing — correct for the feature store, which
    the artifact was made from, and useless for the competition's catalogue,
    which is a later week and which the artifact predates almost entirely. A
    corpus of zero rows would rank every candidate 0 and submit the candidate
    file's own order under the name of a semantic retriever.

    So the rows the artifact misses are encoded here, for a dataset the
    registry says generates its own vectors. One that ships them has nothing
    to encode with — no checkpoint to call and no token width to call it at —
    and its artifact covers the whole release anyway, so its misses stay zero
    and are reported rather than invented.

    Encoding a six-figure catalogue on a CPU is minutes, not seconds, so the
    result is cached under `directory` and reused whenever the corpus it was
    built for is the same one, article for article and in the same order.
    """
    spec = config.embeddings
    corpus_ids = articles["article_id"].astype("string").to_numpy(dtype=object)
    cached = _cached(directory, corpus_ids, spec)
    if cached is not None:
        return cached, {"articles": len(corpus_ids), "cached": 1, "encoded": 0}

    source_ids, source_vectors = read_source(config)
    matrix, missing = align(source_ids, source_vectors, articles["article_id"], spec.dim)
    if spec.normalise:
        matrix = normalise(matrix)

    # What `align` matched by id but the text says is a different article. See
    # stale_rows: across MIND releases that is every shared id but one.
    stale = stale_rows(config, articles) & matrix.any(axis=1)
    matrix[stale] = 0
    missing += int(stale.sum())

    encoded = 0
    if missing and spec.kind == GENERATE:
        rows = np.flatnonzero(~matrix.any(axis=1))
        texts = list(document_text(articles).iloc[rows])
        device = encoding_device()
        print(
            f"    encoding {len(rows):,} articles the artifact does not cover, "
            f"on {device}"
        )
        matrix[rows] = encode(texts, config, device=device)
        encoded = len(rows)

    check_unit_norm(matrix, config)
    embeddings = Embeddings(vectors=matrix, article_ids=corpus_ids)
    embeddings.save(directory)
    (directory / SOURCE).write_text(
        json.dumps(source_identity(spec), indent=2), encoding="utf-8"
    )
    return embeddings, {
        "articles": len(corpus_ids),
        "cached": 0,
        "encoded": encoded,
        # Matched by id and rejected on the text. Reported rather than folded
        # into `missing`, because it is the one number that says the corpus and
        # the artifact disagree about what an id names.
        "stale": int(stale.sum()),
        # What the artifact did cover, and — for a dataset that encodes — what
        # it did not and had to be made here.
        "from_artifact": len(corpus_ids) - missing,
        "missing": missing - encoded,
    }


# Bumped whenever the rule for *which* artifact rows may be reused changes, so
# a matrix cached under the old rule is rebuilt rather than silently reused. 2
# is the rule that checks an id's text before trusting its vector; 1 trusted
# the id alone, and every MIND submission built under it holds a catalogue half
# of which is some other article's vector.
REUSE_RULE = 2


def source_identity(spec: EmbeddingSpec) -> dict[str, object]:
    """Everything about a spec that changes the vectors it produces.

    Not `postprocess`: the correction is applied downstream of this cache, on
    the way into the index, so a matrix cached under one correction is the
    right matrix under another.

    `reuse_rule` is not about the spec at all -- it is about this module. It is
    here because the cache is keyed on this dict, and a corpus matrix built
    when the reuse rule was wrong is wrong in a way no field above can see.
    """
    return {
        "reuse_rule": REUSE_RULE,
        "model": spec.model,
        "dim": spec.dim,
        "artifact": spec.artifact,
        "prefix": spec.prefix,
        "pooling": spec.pooling,
        "encoder": spec.encoder,
        "normalise": spec.normalise,
        "max_tokens": spec.max_tokens,
    }


def _cached(
    directory: Path, corpus_ids: np.ndarray, spec: EmbeddingSpec
) -> Embeddings | None:
    """A previous run's matrix, if it was built for this corpus *and* this model.

    Same ids in the same order or nothing: a matrix is positional, so one built
    for a catalogue that has since gained an article would pair every row after
    that article with the wrong one and still load without complaint.

    And the same source, which the ids cannot tell you. Promoting a new encoder
    does not change the competition's catalogue by one article, so a cache keyed
    on ids alone survives the promotion and hands the submission the *old*
    model's vectors -- unit length, well formed, the right shape when the widths
    happen to agree, and not the model any reported number was measured on.
    That is the one failure a submission path must not have, and it is invisible
    in the output. A matrix with no `source.json` beside it predates this check
    and is not reused.
    """
    if not (directory / VECTORS).exists() or not (directory / ID_INDEX).exists():
        return None

    identity = directory / SOURCE
    if not identity.exists():
        return None
    if json.loads(identity.read_text(encoding="utf-8")) != source_identity(spec):
        return None

    stored = pd.read_parquet(directory / ID_INDEX)["article_id"]
    stored = stored.astype("string").to_numpy(dtype=object)
    if len(stored) != len(corpus_ids) or not (stored == corpus_ids).all():
        return None
    return Embeddings(vectors=np.load(directory / VECTORS), article_ids=stored)


def load(config: DatasetConfig) -> Embeddings:
    """The aligned, unit-length matrix this stage last wrote."""
    directory = output_dir(config)
    ids = pd.read_parquet(directory / ID_INDEX)["article_id"]
    return Embeddings(
        vectors=np.load(directory / VECTORS),
        article_ids=ids.astype("string").to_numpy(dtype=object),
    )


def run(config: DatasetConfig, force: bool = False) -> None:
    """Put the dataset's aligned, unit-length matrix on disk, and report it."""
    directory = output_dir(config)
    if not force and (directory / VECTORS).exists():
        embeddings = load(config)
        print(
            f"    {len(embeddings.article_ids):,} articles x "
            f"{embeddings.vectors.shape[1]} dimensions loaded from {directory}"
        )
        return

    ensure_artifact(config)
    articles = pd.read_parquet(config.feature_store_dir / "articles.parquet")
    embeddings, report = build(articles, config)
    embeddings.save(directory)

    print(
        f"    {report['articles']:,} articles x {report['dim']} dimensions "
        f"from {config.embeddings.model}"
    )
    print(
        f"    anisotropy {report['anisotropy_before']:.4f} -> "
        f"{report['anisotropy_after']:.4f} under {report['postprocess']} "
        f"(mean cosine between two articles; near 0 is informative, near 1 "
        f"means every pair looks alike)"
    )
    if report["missing"]:
        # Named rather than summarised: these articles keep a zero row, so they
        # are never retrieved, and a large count means the artifact and the
        # corpus disagree about what an article id looks like.
        print(
            f"    {report['missing']:,} article(s) have no vector in "
            f"{config.embeddings.artifact} and keep a zero row"
        )
