"""Article embeddings: one dense vector per article, one interface per dataset.

How the vectors are obtained differs — MIND has none and they are generated by
a notebook on a hosted GPU, EB-NeRD ships precomputed multilingual BERT — but
that difference lives in the registry's EmbeddingSpec. Everything below reads
the spec and never the dataset name.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property
from pathlib import Path

import numpy as np
import pandas as pd

from pipeline.datasets import DatasetConfig

# float32 normalisation lands a few ulps off exactly 1.0; anything further out
# than this is a real deviation rather than rounding.
UNIT_TOLERANCE = 1e-5


# The two ways a dataset comes by its vectors, as named in the registry.
GENERATE, PROVIDED = "generate", "provided"

# The article-id-to-row index, saved beside the vectors. The notebook emits
# one of these for MIND and the stage writes one for either dataset.
ID_INDEX = "article_id_index.parquet"

# The aligned, unit-length matrix the stage writes for ticket 8 to load. Named
# apart from the registry's `artifact` so saving it can never overwrite the
# downloaded source it was built from.
VECTORS = "vectors.npy"

# The notebook that produces the generated artifact, named in the error a user
# hits when it has not been run yet.
NOTEBOOK = "notebooks/generate_mind_embeddings.ipynb"


class EmbeddingError(RuntimeError):
    """The embedding artifact does not hold what the pipeline requires of it."""


def align(
    source_ids: np.ndarray,
    source_vectors: np.ndarray,
    corpus_ids: pd.Series,
    dim: int,
) -> tuple[np.ndarray, int]:
    """Reorder the source vectors onto the corpus, one row per article.

    The corpus decides which rows exist and in what order; the artifact is
    only asked what it holds for each. Vectors for articles outside the corpus
    are dropped, and an article the artifact has no vector for keeps its row
    as zeros rather than vanishing — a missing row would put the corpus and
    the matrix permanently out of step, and a zero vector scores zero against
    everything, so it is never retrieved on evidence it does not have.
    """
    row_of = {article_id: row for row, article_id in enumerate(source_ids)}
    matrix = np.zeros((len(corpus_ids), dim), dtype="float32")

    missing = 0
    for row, article_id in enumerate(corpus_ids):
        source_row = row_of.get(article_id)
        if source_row is None:
            missing += 1
            continue
        matrix[row] = source_vectors[source_row]

    return matrix, missing


def normalise(matrix: np.ndarray) -> np.ndarray:
    """Scale every row to unit length, so an inner product is a cosine.

    Rows that are already zero — the articles align found no vector for —
    stay zero rather than becoming NaN. Dividing them through would spread
    NaN across every score the index ever computes, whereas a zero row simply
    never wins a comparison.
    """
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return np.divide(matrix, norms, out=np.zeros_like(matrix), where=norms > 0)


def check_unit_norm(matrix: np.ndarray, config: DatasetConfig) -> None:
    """Every non-zero row must have length one, whoever produced it.

    For EB-NeRD this confirms our own normalisation; for MIND it confirms the
    notebook's `normalize_embeddings=True` actually took effect in the
    artifact that got uploaded, which is otherwise only knowable by reading a
    notebook that ran on someone else's machine.
    """
    norms = np.linalg.norm(matrix, axis=1)
    off = np.abs(norms - 1.0) > UNIT_TOLERANCE
    # A zero row is align reporting a missing vector, not a scaling failure.
    off &= norms > 0

    if off.any():
        worst = norms[off]
        raise EmbeddingError(
            f"{config.name}: {off.sum():,} of {len(norms):,} embedding rows "
            f"are not unit length (norms {worst.min():.4g} to {worst.max():.4g}); "
            f"an inner product over these is not a cosine similarity"
        )


def read_source(config: DatasetConfig) -> tuple[np.ndarray, np.ndarray]:
    """The dataset's vectors as (article ids, matrix), straight from its source.

    Neither the order nor the membership is the corpus's — EB-NeRD's artifact
    covers the whole release, not just the small distribution — so what comes
    back here is only ever handed to `align`.
    """
    spec = config.embeddings
    if spec.kind == PROVIDED:
        frame = pd.read_parquet(config.raw_dir / spec.artifact)
        # The artifact carries the ids and exactly one vector column, named
        # after the model that produced it. Naming that column in the registry
        # too would be a second thing to keep in step with the file.
        columns = [name for name in frame.columns if name != "article_id"]
        if len(columns) != 1:
            raise EmbeddingError(
                f"{config.name}: expected one vector column beside article_id "
                f"in {spec.artifact}, found {columns}"
            )
        vectors = np.stack(
            [np.asarray(row, dtype="float32") for row in frame[columns[0]]]
        )
    else:
        vectors = np.load(config.artifacts_dir / spec.artifact).astype("float32")
        frame = pd.read_parquet(config.artifacts_dir / ID_INDEX)

    # The corpus keys articles by string; EB-NeRD's artifact keys them by
    # int32. Unconverted, align would match nothing and hand back a matrix of
    # zeros that every later stage would read as a very poor retriever.
    return frame["article_id"].astype("string").to_numpy(dtype=object), vectors


@dataclass(frozen=True)
class Embeddings:
    """One dataset's article vectors, and what turns an id into a row.

    Row i belongs to article_ids[i], and article_ids is the article catalogue
    in catalogue order — so a row number and a catalogue position are the same
    thing, whichever way the dataset came by its vectors.
    """

    vectors: np.ndarray
    article_ids: np.ndarray

    @cached_property
    def index(self) -> dict[str, int]:
        """article id -> row. Built once; ticket 8 does a lookup per click."""
        return {article_id: row for row, article_id in enumerate(self.article_ids)}

    def save(self, directory: Path) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        np.save(directory / VECTORS, self.vectors)
        pd.DataFrame({"article_id": pd.Series(self.article_ids, dtype="string")}
                     ).to_parquet(directory / ID_INDEX, index=False)


def build(articles: pd.DataFrame, config: DatasetConfig) -> tuple[Embeddings, dict]:
    """The dataset's vectors, aligned to its catalogue and unit length.

    Whether the scaling happens here or happened upstream is a registry
    decision; that it holds afterwards is checked either way, because ticket
    8 calls the inner product of these a cosine similarity.
    """
    spec = config.embeddings
    source_ids, source_vectors = read_source(config)

    width = source_vectors.shape[1]
    if width != spec.dim:
        raise EmbeddingError(
            f"{config.name}: {spec.artifact} holds {width}-dimensional "
            f"vectors, but the registry declares {spec.dim}"
        )

    corpus_ids = articles["article_id"]
    matrix, missing = align(source_ids, source_vectors, corpus_ids, spec.dim)
    if spec.normalise:
        matrix = normalise(matrix)
    check_unit_norm(matrix, config)

    embeddings = Embeddings(
        vectors=matrix, article_ids=corpus_ids.to_numpy(dtype=object)
    )
    report = {"articles": len(corpus_ids), "dim": spec.dim, "missing": missing}
    return embeddings, report


def ensure_artifact(config: DatasetConfig) -> None:
    """Put the generated artifact on disk if it is not already there.

    A dataset whose vectors ship with it has nothing to fetch. For one that
    generates them, the artifact is a build output rather than source, so it
    is downloaded on demand instead of being committed — and once it is here
    it is used as it stands, with no network call to confirm it.
    """
    spec = config.embeddings
    if spec.kind != GENERATE:
        return

    vectors = config.artifacts_dir / spec.artifact
    index = config.artifacts_dir / ID_INDEX
    if vectors.exists() and index.exists():
        return

    if spec.gdrive_file_id is None:
        raise EmbeddingError(
            f"{config.name}: no embeddings on disk and no artifact to fetch.\n"
            f"  {config.name} ships no vectors, so they are generated once on a "
            f"hosted GPU rather than rebuilt on every machine:\n"
            f"    1. run {NOTEBOOK} on Colab with a T4 runtime\n"
            f"    2. upload its {spec.artifact} and {ID_INDEX} to Drive, shared "
            f"so that anyone with the link can read them\n"
            f"    3. put the folder's id in gdrive_file_id on {config.name}'s "
            f"EmbeddingSpec in pipeline/datasets.py\n"
            f"  then re-run this stage."
        )

    # Imported here because it is only ever needed on the one path that
    # downloads, and only until the artifact is cached locally.
    import gdown

    config.artifacts_dir.mkdir(parents=True, exist_ok=True)
    gdown.download_folder(
        id=spec.gdrive_file_id, output=str(config.artifacts_dir), quiet=False
    )

    absent = [path.name for path in (vectors, index) if not path.exists()]
    if absent:
        raise EmbeddingError(
            f"{config.name}: the download from Drive folder "
            f"{spec.gdrive_file_id} left no {', '.join(absent)} in "
            f"{config.artifacts_dir}"
        )


def load(config: DatasetConfig) -> Embeddings:
    """The aligned, unit-length matrix this stage last wrote."""
    directory = config.artifacts_dir
    ids = pd.read_parquet(directory / ID_INDEX)["article_id"]
    return Embeddings(
        vectors=np.load(directory / VECTORS),
        article_ids=ids.astype("string").to_numpy(dtype=object),
    )
