"""BM25's parameters, measured rather than inherited.

k1, b and the title weight were never tuned: the first two were copied from
SPEC.md and the third did not exist -- title and abstract were concatenated into
one bag, which scores a term in a six-word headline exactly as it scores one in
a forty-word abstract.

Swept on the tune split, all three axes together rather than one after another,
because they interact: repeating a title lengthens the document, and `b` is the
weight on document length.

The queries are built from clicked *titles* and so depend on none of the three
axes. They are built once and reused across every cell, which is part of why
this grid is minutes rather than hours; the other part is `score_pairs`, which
reads each candidate's own term weights out of the index rather than scoring
the whole corpus once per impression. On EB-NeRD that is the difference between
three minutes a cell and a few seconds.
"""

from __future__ import annotations

import argparse
import dataclasses
import itertools
import json
import time

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

from pipeline import bm25_index, embed_compare, evaluate, paths, preprocess, retrieval
from pipeline.datasets import DATASETS, DatasetConfig

K1 = (0.6, 0.9, 1.2, 1.5, 2.0)
B = (0.0, 0.3, 0.5, 0.75, 0.9)
TITLE_WEIGHT = (1, 2, 3)

RESULTS = "lexical-{split}.jsonl"
DOCUMENT = "lexical-{split}.md"


def per_impression_auc(
    scores: np.ndarray, widths: np.ndarray, labels: list[list[int]]
) -> np.ndarray:
    """AUC per impression, on the ones where it is defined.

    `scores` is every (impression, candidate) pair concatenated in the order
    the candidate lists were given — which is the order the labels are in too,
    and the reason this is the path the sweep takes. The ranked path returns
    its scores **sorted best-first and aligned to `ranked_ids`**, and zipping
    those against input-order labels is exactly a random pairing: it produced a
    grid of 0.4985, a perfect coin flip, that read as a real finding about BM25
    on short news documents rather than as a bug.

    Undefined where every candidate is clicked or none is. An impression the
    retriever scored flat is kept and scores 0.5: a flat ranking is a real
    outcome for a lexical retriever whose query shares no term with anything,
    and dropping those would quietly measure a different population per cell.
    """
    values = []
    starts = np.cumsum(widths) - widths
    for start, width, marks in zip(starts, widths, labels):
        truth = np.asarray(marks)
        if truth.sum() == 0 or truth.sum() == len(truth):
            continue
        against = scores[start : start + width].astype("float64")
        values.append(0.5 if np.ptp(against) == 0 else roc_auc_score(truth, against))
    return np.asarray(values)


def document(rows: list[dict], name: str, split: str) -> str:
    best = max(rows, key=lambda r: r["auc"])
    baseline = next(
        (r for r in rows if (r["k1"], r["b"], r["title_weight"]) == (1.5, 0.75, 1)),
        None,
    )
    lines = [
        f"# BM25 parameters — {name}, {split} split",
        "",
        f"`k1` x `b` x title weight, {len(rows)} cells on the **{split}** split. "
        f"Generated by `python -m pipeline.lexical_sweep`.",
        "",
        "- **k1** is term-frequency saturation, **b** the weight on document-length "
        "normalisation, and the title weight repeats the headline's tokens so a term "
        "in it outranks the same term in an abstract.",
        "- A difference is a difference only where the intervals are disjoint.",
        "",
        "| k1 | b | title weight | auc | 95% interval |",
        "| ---: | ---: | ---: | ---: | --- |",
    ]
    for row in sorted(rows, key=lambda r: -r["auc"]):
        lines.append(
            f"| {row['k1']} | {row['b']} | {row['title_weight']} | "
            f"{row['auc']:.4f} | [{row['lo']:.4f}, {row['hi']:.4f}] |"
        )
    lines += ["", "## Reading", ""]
    lines.append(
        f"- Best: **k1={best['k1']}, b={best['b']}, title weight "
        f"{best['title_weight']}** (auc {best['auc']:.4f} "
        f"[{best['lo']:.4f}, {best['hi']:.4f}])."
    )
    if baseline is not None:
        gap = best["auc"] - baseline["auc"]
        established = best["lo"] > baseline["hi"]
        lines.append(
            f"- The inherited setting k1=1.5, b=0.75, weight 1 scores "
            f"{baseline['auc']:.4f} [{baseline['lo']:.4f}, {baseline['hi']:.4f}], "
            f"so the sweep is worth {gap:+.4f} and the difference **is"
            f"{'' if established else ' not'}** established by disjoint intervals."
        )
    overlapping = [
        r for r in rows
        if r is not best and r["hi"] >= best["lo"] and r["lo"] <= best["hi"]
    ]
    lines.append(
        "- Those intervals are **unpaired**, and every cell scores the same "
        "impressions: most of their width is the variance between impressions "
        "rather than between settings, which cancels in a difference. So they "
        "are a conservative bound and not the test — `pipeline.lexical_ablation` "
        "runs the paired one on the setting this grid nominates."
    )
    lines.append(
        f"- {len(overlapping)} of {len(rows) - 1} other cells overlap the best one's "
        f"interval, so the surface is "
        f"{'flat and the argmax is largely noise' if len(overlapping) > len(rows) // 2 else 'peaked rather than flat'}."
    )
    return "\n".join(lines) + "\n"


def run(config: DatasetConfig, split: str, resamples: int) -> list[dict]:
    articles = pd.read_parquet(config.feature_store_dir / "articles.parquet")
    scored = embed_compare.impressions(config, split)
    print(f"  {len(scored):,} {split} impressions", flush=True)

    # Queries come from clicked titles, so no axis of this grid moves them.
    clicks = pd.DataFrame(
        {
            "impression_id": scored["impression_id"],
            "click_history": scored["click_history"],
        }
    )
    queries, _ = bm25_index.build_queries(
        clicks, articles, config, retrieval.HISTORY_K
    )
    tokens = [query.split() for query in queries["query"]]
    candidates = list(scored["candidate_ids"])
    labels = list(scored["labels"])
    widths = np.fromiter((len(c) for c in candidates), dtype="int64", count=len(candidates))

    rows: list[dict] = []
    for weight in TITLE_WEIGHT:
        corpus = articles.copy()
        corpus["lexical_text"], _ = preprocess.build_lexical_text(
            articles, config, title_weight=weight
        )
        for k1, b in itertools.product(K1, B):
            started = time.perf_counter()
            tuned = dataclasses.replace(
                config, lexical=dataclasses.replace(config.lexical, k1=k1, b=b)
            )
            index = bm25_index.build(corpus, tuned)
            values = per_impression_auc(
                index.score_pairs(tokens, candidates), widths, labels
            )
            low, high = embed_compare.interval(values, resamples)
            rows.append(
                {
                    "dataset": config.name, "split": split,
                    "k1": k1, "b": b, "title_weight": weight,
                    "auc": float(values.mean()) if len(values) else 0.0,
                    "n": int(len(values)), "lo": low, "hi": high,
                    "seconds": round(time.perf_counter() - started, 1),
                }
            )
            print(
                f"    k1={k1:<4} b={b:<5} weight={weight}  auc "
                f"{rows[-1]['auc']:.4f} [{low:.4f}, {high:.4f}]",
                flush=True,
            )
    return rows


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dataset", choices=sorted(DATASETS), default="mind")
    parser.add_argument("--split", default=evaluate.TUNE, choices=evaluate.SCORABLE)
    parser.add_argument("--resamples", type=int, default=evaluate.BOOTSTRAP_RESAMPLES)
    args = parser.parse_args(argv)

    config = DATASETS[args.dataset]
    rows = run(config, args.split, args.resamples)

    paths.ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    suffix = f"{config.name}-{args.split}"
    with (paths.ARTIFACTS_DIR / RESULTS.format(split=suffix)).open("w") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")
    text = document(rows, config.name, args.split)
    (paths.ARTIFACTS_DIR / DOCUMENT.format(split=suffix)).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
