"""All three retrievers side by side, from the stored evaluation reports.

    python -m pipeline.three_way

`compare.py` answers the assignment's question — lexical against semantic — and
is built around that pair the whole way down: a `Comparison` holds a `lex` and a
`sem`, and its delta is one minus the other. Generalising it to N retrievers
would rewrite a working, tested module to say something it was not asked to say.
So the hybrid gets its own document, under its own name, and the two never hold
the same numbers under the same title.

It ranks nothing itself. Everything here is read out of
`artifacts/<dataset>/evaluate/<retriever>-<split>.json`, so this document cannot
disagree with the harness — it can only fail to find a report that was never
written.
"""

from __future__ import annotations

import argparse
import json

from pipeline import evaluate, ingest, paths
from pipeline.datasets import DATASETS, DatasetConfig

DOCUMENT = "three-way-{split}.md"

# The order they are reported in: the two parents, then what was built from
# them. Not sorted by score -- the point of the table is the comparison, and a
# table that reorders itself per dataset is harder to read across datasets.
ORDER = ("bm25", "ann", "hybrid")

METRICS = ("auc", "mrr", "ndcg@5", "ndcg@10")


class MissingReport(RuntimeError):
    """A retriever has not been scored on this split."""


def load(config: DatasetConfig, retriever: str, split: str) -> dict:
    path = config.artifacts_dir / evaluate.EVALUATE_DIR / f"{retriever}-{split}.json"
    if not path.exists():
        raise MissingReport(
            f"{path} not found — run `python -m pipeline.evaluate --dataset "
            f"{config.name} --retriever {retriever} --split {split}` first"
        )
    stored = json.loads(path.read_text())
    return {
        row["metric"]: row
        for row in stored["results"]
        if row["slice"] == "overall" and row["metric"] in METRICS
    }


def paired_gap(config: DatasetConfig, split: str, resamples: int) -> dict:
    """The hybrid against its better parent, paired by impression, on `split`.

    Not a second selection. The rule and the parameter were fixed on `tune`;
    this re-ranks that one fixed configuration and asks how it differs from the
    better parent on the split results are reported on. Reporting a paired
    difference is the honest instrument for two retrievers that score the same
    impressions -- the per-retriever intervals above are dominated by variance
    between impressions and cannot separate anything at this effect size.

    It costs a fresh ranking pass, and on EB-NeRD BM25's is ten minutes, which
    is why it is opt-in rather than part of every document.
    """
    import pandas as pd

    from pipeline import ann_index, bm25_index, embed_compare, hybrid

    store = config.feature_store_dir
    behaviors = pd.read_parquet(store / "behaviors.parquet")
    impressions = behaviors[behaviors["split"] == split]
    history = ingest.history_for(config, impressions)

    of = {
        impression: dict(zip(candidates, marks, strict=True))
        for impression, candidates, marks in zip(
            impressions["impression_id"],
            impressions["candidate_ids"],
            impressions["labels"],
        )
    }
    labels = lambda frame: [of[i] for i in frame["impression_id"]]

    ranked = {
        "bm25": bm25_index.rank_candidates(config, impressions, history),
        "ann": ann_index.rank_candidates(config, impressions, history),
    }
    measured = {
        name: evaluate.per_impression_metrics(frame, labels(frame))
        for name, frame in ranked.items()
    }
    fused = hybrid.fuse(ranked, config.hybrid)
    values = evaluate.per_impression_metrics(fused, labels(fused))

    better = max(measured, key=lambda name: measured[name]["auc"].mean())
    gap = values["auc"] - measured[better]["auc"]
    low, high = embed_compare.interval(gap, resamples)
    return {
        "against": better,
        "gap": float(gap.mean()),
        "lo": low,
        "hi": high,
        "established": low > 0 or high < 0,
    }


def document(split: str, datasets: list[str], paired: dict | None = None) -> str:
    lines = [
        f"# Three retrievers — {split} split",
        "",
        f"Lexical, semantic, and the two fused, on the **{split}** split. "
        f"Generated by `python -m pipeline.three_way` from the stored "
        f"evaluation reports; nothing here is transcribed by hand.",
        "",
        "The hybrid's rule and its parameter were chosen on `tune` — see "
        "`hybrid-<dataset>-tune.md` for the grid and the paired intervals it "
        "was chosen with. What follows is that choice reported on a split it "
        "was not chosen on.",
    ]

    for name in datasets:
        config = DATASETS[name]
        spec = config.hybrid
        setting = (
            f"`rrf`, k={spec.k:g}" if spec.rule == "rrf"
            else f"`linear`, alpha={spec.alpha:g}"
        )
        reports = {r: load(config, r, split) for r in ORDER}

        lines += [
            "",
            f"## {name}",
            "",
            f"Hybrid: {setting} — alpha weights the lexical side, so "
            f"{spec.alpha:g} means it leans "
            f"{'semantic' if spec.alpha < 0.5 else 'lexical'}.",
            "",
            "| retriever | " + " | ".join(METRICS) + " |",
            "| --- | " + " | ".join("---:" for _ in METRICS) + " |",
        ]
        for retriever in ORDER:
            row = reports[retriever]
            cells = " | ".join(f"{row[m]['value']:.4f}" for m in METRICS)
            lines.append(f"| {retriever} | {cells} |")

        lines += ["", "| retriever | auc | 95% interval |", "| --- | ---: | --- |"]
        for retriever in ORDER:
            row = reports[retriever]["auc"]
            lines.append(
                f"| {retriever} | {row['value']:.4f} | "
                f"[{row['lo']:.4f}, {row['hi']:.4f}] |"
            )

        best_parent = max(("bm25", "ann"), key=lambda r: reports[r]["auc"]["value"])
        parent = reports[best_parent]["auc"]
        fused = reports["hybrid"]["auc"]
        gap = fused["value"] - parent["value"]
        disjoint = fused["lo"] > parent["hi"] or parent["lo"] > fused["hi"]

        lines += ["", "**Reading.** "]
        lines[-1] += (
            f"The better parent is `{best_parent}` at {parent['value']:.4f}. "
            f"The hybrid scores {fused['value']:.4f}, {gap:+.4f} against it, "
            f"and the two intervals are **{'disjoint' if disjoint else 'overlapping'}**. "
        )
        lines[-1] += (
            "Those are the **unpaired** per-retriever intervals, which are "
            "dominated by variance between impressions rather than between "
            "retrievers and so overlap at any effect size this project can "
            "produce. They are a floor, not the test."
        )

        found = (paired or {}).get(name)
        if found:
            lines += [
                "",
                f"Paired by impression against `{found['against']}`, on this "
                f"same split: **{found['gap']:+.4f}** "
                f"[{found['lo']:+.4f}, {found['hi']:+.4f}] — the difference "
                f"**is{'' if found['established'] else ' not'}** established. "
                + (
                    "The rule and the parameter were fixed on `tune`; this is "
                    "that fixed configuration measured here, not a second "
                    "selection."
                    if found["established"]
                    else "So the hybrid cannot be told from its better parent "
                    "on this dataset, which is the honest result and is worth "
                    "more than a tuned number."
                ),
            ]

    lines += [
        "",
        "## What this does not say",
        "",
        "- **Nothing about retrieval depth.** These are re-ranking metrics over "
        "each impression's own candidates. The hybrid's `retrieve_corpus` fuses "
        "what the two parents retrieved and is reported by the sweep, not here.",
        "- **Nothing chosen on this split.** Every parameter behind these rows "
        "was selected on `tune`. A number that came out smaller here than it did "
        "there is the ordinary cost of holding a split back, not a reason to "
        "re-pick.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--split", default=evaluate.VALIDATION, choices=evaluate.SCORABLE)
    parser.add_argument(
        "--dataset", action="append", choices=sorted(DATASETS),
        help="restrict to one dataset (repeatable); default is all of them",
    )
    parser.add_argument(
        "--paired",
        action="store_true",
        help="also re-rank and report the paired difference against the better "
        "parent (costs a fresh ranking pass per dataset)",
    )
    parser.add_argument("--resamples", type=int, default=evaluate.BOOTSTRAP_RESAMPLES)
    args = parser.parse_args(argv)

    datasets = args.dataset or sorted(DATASETS)
    paired = None
    if args.paired:
        paired = {}
        for name in datasets:
            print(f"  pairing {name} on {args.split} ...", flush=True)
            paired[name] = paired_gap(DATASETS[name], args.split, args.resamples)
    text = document(args.split, datasets, paired)
    paths.ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    written = paths.ARTIFACTS_DIR / DOCUMENT.format(split=args.split)
    written.write_text(text)
    print(text)
    print(f"  -> {written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
